### ISSUE TITLE
Create repositories for runners and scm

### ISSUE THREAD

**Issue by haklop** [bazooka-ci/bazooka#136]
Extract runner and scm folders into their owns repositories.

**Comment by julienvey** [comment]
+1 
We can set up Docker automated build for this repo, and we can still update them for development purposes if needed

Question is:  
* one repo per runner/scm (one for runner-java, one for runner-golang.....)
* one repo for all runners and one repo for all scm 

@jawher What's your opinion on this ?

**Comment by jawher** [comment]
I'd go with one repo per language and one repo per scm for the sake of *potential* contributors:

* Focused Issues: no need for a bazillion tags
* Focused build/tests: if you fork the golang repository, you just run make and it will only build the golang runner, instead of golang, java, python, etc. No need to remember to do make golang for example.

**Comment by jawher** [comment]
One suggestion: should we group the parser and runner for every supported language in one repo ?
